name: tick_tock
description: "The greatest super app ever made"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  flutter_bloc: ^8.1.6
  collection: ^1.18.0
  flutter_local_notifications: ^18.0.1
  timezone: any
  permission_handler: ^11.3.1
  dio: ^5.4.3+1
  sembast: ^3.7.1+2
  path_provider: ^2.1.3
  path: ^1.9.0
  google_fonts: ^6.2.1
  speech_to_text: ^6.6.2
  wave_divider: ^0.0.3
  uuid: ^4.4.2
  freezed_annotation: any
  delightful_toast: ^1.1.0
  fluttertoast: 8.2.10
  grouped_list: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: any
  build_runner: any
  json_serializable: any
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
